name: Proposition de modification de transcription
description: Proposer une correction de transcription dans un document.
title: "Proposition de modification de transcription"
labels: ["Suggestion de modification"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist préalable
      options:
        - label: J'ai pris connaissance des [règles de transcription](TRANSCRIPTION_RULES.md).
          required: true

  - type: input
    id: location
    attributes:
      label: Où se trouve la modification souhaitée ?
      description: >
        Indique la position précise dans le document original.
        Minimum requis : référence de la page photographiée.
      placeholder: "Ex : Lettre du mercredi 01 septembre 1954 de J-M à M-M — page 4"

  - type: input
    id: correction
    attributes:
      label: Description des modifications souhaitées
      description: |
        Décris la transcription actuelle, la correction proposée et la justification.
      value: |
        Je lis : "..."
        Je pense que je devrais lire : "..."
        Justification : "..."

  - type: textarea
    id: example
    attributes:
      label: Exemple
      description: Exemple de correction pertinente
      value: |
        Je lis : "Mais revenons aux choses serieuses."
        Je pense que je devrais lire : "Mais revenons aux choses sérieuses."
        Justification : Il manque un accent à "sérieuses"


  - type: textarea
    id: context
    attributes:
      label: Contexte (optionnel)
      description: |
        Inclure plus de contexte si la modifications souhaitée est difficile à expliquer/comprendre (Capture d'écran, ressource orthographique utile, ...)
      required: false